name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache cnpm packages
        uses: actions/cache@v2
        env:
          cache-name: cache-cnpm-packages
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-cache-cnpm-packages-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            cache-cnpm-packages-

      - name: Install cnpm
        run: npm install -g cnpm

      - name: Install dependencies
        run: cnpm install

      - name: Run ci
        run: cnpm run ci
